### ISSUE TITLE
Its not letting me install it

### ISSUE THREAD

**Issue by ashercn97** [msaelices/py2mojo#1]
??

**Comment by ashercn97** [comment]
@msaelices When i try to pip install it, it says it isnt a thing

**Comment by ashercn97** [comment]
nvm got it working! for anyone who sees this the steps i  took where:

clone the repo
cd py2mojo
pip install e .
then it worked!

**Comment by msaelices** [comment]
Sorry, it's not published yet in pypi. It's still at a very early stage.

**Comment by msaelices** [comment]
I've just published the package to pypi

**Comment by ashercn97** [comment]
@msaelices Okay great! I did it through the pip install e . but i will do it through pypi!
